### ISSUE TITLE
Some bugs with Bootstrap 3.0.0

### ISSUE THREAD

**Issue by raelb** [mistic100/Bootstrap-Confirmation#41]
Hi,

I encountered some bugs with Bootstrap v3.0.0. For one, console shows this error:
Uncaught TypeError: this.getUID is not a function

Strangely, when used in my asp.net mvc app I did not get this console message, however I was running into some behaviour bugs. When I upgraded to 3.3.7 the behaviour bugs no longer occurred.

**Comment by mistic100** [comment]
The Bower dependency is marked as >=3.2 on purpose :-)
